"""Enable PostgreSQL spatial extensions and operational geospatial tables.

Revision ID: 0002_postgis_operational_schema
Revises: 0001_initial
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0002_postgis_operational_schema"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    for extension in ("postgis", "pgrouting", "pgcrypto", "btree_gist"):
        op.execute(f'CREATE EXTENSION IF NOT EXISTS "{extension}"')

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS normalized_source_records (
            id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            incident_id text NOT NULL,
            provider text NOT NULL,
            source_id text NOT NULL,
            source_url text,
            observed_at timestamptz,
            acquired_at timestamptz,
            issued_at timestamptz,
            ingested_at timestamptz NOT NULL DEFAULT now(),
            valid_from timestamptz,
            valid_until timestamptz,
            coverage geometry(Geometry, 4326),
            confidence double precision NOT NULL CHECK (confidence BETWEEN 0 AND 1),
            quality_flags jsonb NOT NULL DEFAULT '[]'::jsonb,
            licence text NOT NULL,
            attribution text NOT NULL,
            checksum_sha256 text NOT NULL CHECK (length(checksum_sha256) = 64),
            dataset_version text NOT NULL,
            raw_reference text NOT NULL,
            is_simulated boolean NOT NULL DEFAULT false,
            UNIQUE (provider, source_id, dataset_version)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_source_records_coverage "
        "ON normalized_source_records USING gist (coverage)"
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS simulation_snapshots (
            id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            incident_id text NOT NULL,
            snapshot_version text NOT NULL UNIQUE,
            source_versions jsonb NOT NULL,
            snapshot_payload jsonb NOT NULL,
            checksum_sha256 text NOT NULL CHECK (length(checksum_sha256) = 64),
            created_at timestamptz NOT NULL DEFAULT now(),
            is_simulated boolean NOT NULL DEFAULT false
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS model_artifacts (
            id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            incident_id text NOT NULL,
            snapshot_version text NOT NULL REFERENCES simulation_snapshots(snapshot_version),
            model_version text NOT NULL,
            artifact_type text NOT NULL,
            object_key text NOT NULL,
            checksum_sha256 text NOT NULL CHECK (length(checksum_sha256) = 64),
            horizon_minutes integer NOT NULL CHECK (horizon_minutes IN (0, 30, 60, 180)),
            quantile text NOT NULL CHECK (quantile IN ('p10', 'p50', 'p90', 'agreement')),
            valid_at timestamptz NOT NULL,
            created_at timestamptz NOT NULL DEFAULT now(),
            UNIQUE (model_version, artifact_type, horizon_minutes, quantile)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS route_edges (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            graph_version text NOT NULL,
            source bigint NOT NULL,
            target bigint NOT NULL,
            geom geometry(LineString, 4326) NOT NULL,
            base_cost double precision NOT NULL CHECK (base_cost >= 0),
            reverse_cost double precision NOT NULL,
            p50_depth_m double precision,
            p90_depth_m double precision,
            authorized_closed boolean NOT NULL DEFAULT false,
            is_bridge boolean NOT NULL DEFAULT false,
            is_tunnel boolean NOT NULL DEFAULT false,
            evidence_version text,
            model_version text,
            valid_until timestamptz
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_route_edges_geom ON route_edges USING gist (geom)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_route_edges_graph_source_target "
        "ON route_edges (graph_version, source, target)"
    )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.execute("DROP TABLE IF EXISTS route_edges")
    op.execute("DROP TABLE IF EXISTS model_artifacts")
    op.execute("DROP TABLE IF EXISTS simulation_snapshots")
    op.execute("DROP TABLE IF EXISTS normalized_source_records")
